default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
  timeout: 5000

development:
  <<: *default
  database: shopifiable_dev

test:
  <<: *default
  database: shopifiable_test

production:
  <<: *default
  database: shopifiable_prod
